all:
  hosts:
    v2ha-k8s-node1:
      ansible_host: 192.168.1.1
      ip: 192.168.1.1
      access_ip: 192.168.1.1
    v2ha-k8s-node2:
      ansible_host: 192.168.1.2
      ip: 192.168.1.2
      access_ip: 192.168.1.2
    v2ha-k8s-node3:
      ansible_host: 192.168.1.3
      ip: 192.168.1.3
      access_ip: 192.168.1.3
  children:
    kube_control_plane:
      hosts:
        v2ha-k8s-node1:
        v2ha-k8s-node2:
        v2ha-k8s-node3:
    kube_node:
      hosts:
        v2ha-k8s-node1:
        v2ha-k8s-node2:
        v2ha-k8s-node3:
    etcd:
      hosts:
        v2ha-k8s-node1:
        v2ha-k8s-node2:
        v2ha-k8s-node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}